
		<nav id="skyhog_nav">
			<ul>
				<li><a href="pages.php">Pages</a></li>
				<li><a href="menu.php">Menu</a></li>
				<li><a href="git.php">git</a></li>
				<li><a href="phpliteadmin.php">PHPLiteAdmin</a></li>
				<li><a href="#">System</a>
				<ul>
					<li><a href="setup.php">Maintenance</a></li>
					<li><a href="git.php?CMS_update=1">Update</a></li>
					<li><a href="users.php">Users</a></li>
				</ul></li>
			</ul>
		</nav>