<?
/*
Copyright 2012 Hannes Rauhe

This file is part of Skyhog.

Skyhog is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
	
Skyhog is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Skyhog.  If not, see <http://www.gnu.org/licenses/>.
*/
?>
<footer>
	<p><?php 
	if(isset($a) && $a->isAuth()) {
		echo "Logged in as ".$a->getAuthUserName(); 
	} else {
		echo "You're not logged in.";		
	}
	if(isset($s) && $s->getSiteID()!=-1) {
	    echo " Currently working on ".$s->getSiteName();
        echo " (<a href=\"sites.php\">Change</a>)";
	}
	?>
	</p>
</footer>