<?php
/*
Copyright 2012 Hannes Rauhe

This file is part of Skyhog.

Skyhog is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
	
Skyhog is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Skyhog.  If not, see <http://www.gnu.org/licenses/>.
*/
?>
		<nav id="skyhog_nav">
			<ul>
				<li><a href="pages.php">Pages</a></li>
				<li><a href="template.php">Template</a></li>
				<li><a href="git.php">git</a></li>
                <?php if(isset($a) && $a->isAdmin()): ?>
				<li><a href="#">System</a>
				<ul>
					<li><a href="setup.php">Maintenance</a></li>
                    <?php if(defined("PHPSQLITEADMIN_PASSWD")): ?>
					<li><a href="setup/phpliteadmin.php">PHPLiteAdmin</a></li>
                    <?php endif; ?>
					<li><a href="git.php?CMS_update=1">Update</a></li>
					<li><a href="users.php">Users</a></li>
					<li><a href="settings.php">Settings</a></li>
				</ul></li>				
                <?php endif; ?>
			</ul>
		</nav>